services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
        depends_on:
            - database

    database:
       image: postgres:${POSTGRES_VERSION:-16}-alpine
       environment:
          POSTGRES_DB: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_USER: dev
       ports:
           - 5433:5432
       volumes:
         - ./data/db/postgres:/var/lib/postgresql
