### Calculate Price
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}


Response:
200 OK
{
"price": 109
}'
'
400 Bad Request
{
"error": "couponCode This value is too long. It should have 3 characters or less."
}

### Execute Purchase
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}

Response:
200 OK
{
"accept": true
}
'
400 Bad Request
{
"error": "paymentType The value you selected is not a valid choice."
}